### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by ricardokleinklein** [ricardokleinklein/trial_clustering#1]
## Preprocessing
- [x] Load data
- [x] Find missing values
- [x] Find outliers
- [x] Compute distribution of data (max, min, mean, var)
- [x] Normalize data
- [x] Distribution of data for each attribute
- [x] Correlation between attributes

## Feature extraction
- [x] PCA
- [x] Autoencoder
- [x] LDA
- [x] ICA
- [x] NMF

## Feature discrimination
- [x] Choose feature of interest

## Clustering
- [x] KNN
- [x] k-Means
- [x] GMM

## Visualization

**Comment by ricardokleinklein** [comment]
## About preprocessing:
- No outliers found with interquartile method.
* Although no real outliers have been considered, in attributes 10 and 12 there are values considerably higher than the rest. They are part of an increasing sequence, though, so they haven't been regarded as outliers in the end.
* All data attributes follow a distribution that can be reasonably well fit by a Gaussian distribution. Even Parameters 10 and 12, after removal of largest values show this pattern. 
* Typical distribution of the data
![parameter-5](https://user-images.githubusercontent.com/7894859/37552521-8a73f724-29fa-11e8-8d01-31885b17d817.png)
* Parameter 10 complete
![parameter-10](https://user-images.githubusercontent.com/7894859/37552524-973382fe-29fa-11e8-9828-991af04f12bc.png)
* Parameter 10 with  fewer values
![figure_1](https://user-images.githubusercontent.com/7894859/37552526-a3984cc8-29fa-11e8-80dc-3896f34d3a0e.png)

- No missing values.
- Attributes 1 (Parameter-1) and 4 (Parameter-5) are integers, others are float.

**Comment by ricardokleinklein** [comment]
### About feature extraction:
- The PCA analysis didn't show great results. It seems there is a pattern in a higher dimensional space, but it cannot be appreciated in 2d or 3d.
- 2D plot of the principal components (smaller axis is minor axis):
![figure_1](https://user-images.githubusercontent.com/7894859/37552730-0616889e-29fe-11e8-9bcc-85277763c748.png)


- 3D plot of the principal components:
